import { prisma } from "../../prisma";
import { top50 } from "~~/server/lists/top50";
import { transformDocument } from "@prisma/client/runtime";

export default defineEventHandler(async (event) => {
    const reversals = (
        await prisma.player.findMany({
            select: {
                name: true,
                id: true,
                _count: {
                    select: {
                        accoladeLosses: {
                            where: {
                                shortName: "reverse30",
                            },
                        },
                    },
                },
                accoladeLosses: {
                    where: {
                        shortName: "reverse30",
                    },
                    select: {
                        tournament: {
                            select: {
                                name: true,
                            },
                        },
                    },
                },
            },
        })
    ).sort((a, b) => b._count.accoladeLosses - a._count.accoladeLosses);

    return reversals;
});

const playerList = [
    "FullStream",
    "MrLz",
    "Ralph",
    "CakeAssault",
    "Arcanine",
    "Kaos",
    "AZCards",
    "LBO",
    "MSB",
    "Kisuno",
    "DolphinBrick",
    "TheFailWhale",
    "Turquoise",
    "Handbuttt",
    "PikaThePikachu",
    "ProDoubleSushi",
    "Kenneth",
    "Atma",
    "TurtleBox",
    "GracefulKnight",
    "RiskyCB",
    "Windows",
    "Aurecia",
    "TheEvets",
    "TheDuoDesign",
    "Ceztellz",
    "Protagify",
    "Geqqo",
    "Tandori",
    "Guyron",
    "Dunk",
    "Penguin",
    "Sino",
    "Cupz",
    "JCOnyx",
    "Alexis",
    "Jorane",
    "Bumblebomb",
    "Quote_a",
    "MiNi",
    "Jesier",
    "TheBestAdamCarra",
    "GamingClan",
    "Allergic to Bullets",
    "Mephiles",
    "Renzo",
    "Nevereatcars",
    "SisterEden",
    "Mang0",
    "Solar",
    "Heyodogo",
    "Lord Bagel",
    "SBS",
    "ZeeBee",
    "Dynla",
    "Gaming",
    "Risky",
    "Mugi",
    "geck-0",
    "Dam Danny",
    "Shadow",
    "Adi",
    "hoppyKnitz",
    "Sparx21",
    "ITS A CAT",
    "Corkxx",
    "Seggo",
    "sawsebawse",
    "WooF",
    "Pepe",
    "Skittles",
    "Vaporeon",
    "yesdefinitely",
    "You",
    "MattyIce",
    "Blue",
    "Bullets",
    "Chompers",
    "Hatz",
    "DosRogers",
    "Theomach",
    "Tapscott",
    "DankRamenBoy",
    "Randle",
    "Autumn",
    "culex",
    "Lucius",
    "Xaro",
    "Nero",
    "Jackie Peanuts",
    "Dr Nitronio",
    "Shotti",
    "Akashi",
    "Cheesedog",
    "ProuxEXE",
    "Stroder",
    "Forrest",
    "Backpack",
    "Guard",
    "Bagel",
    "Lattim",
    "Kobra",
    "PrimeTime",
    "O-Gazm",
    "Giga Bowser",
    "starbos",
    "Kruz",
    "Plastic Dinos",
    "CheesyPotato",
    "Levin",
    "Marx",
    "Kaaeru",
    "Spook",
    "Danzello",
    "Junuh",
    "Nexplosion",
    "kusi",
    "Squanto",
    "Halite",
    "Flarey",
    "hoppyknitz",
    "1stDan",
    "HKP",
    "Soulrifle211",
    "Mentos",
    "Ceroas",
    "Buster",
    "Nbad",
    "elpe",
    "Zora",
    "Death By Hugs",
    "Wai",
    "Mr. Olsen",
    "darai",
    "CRSDCrusader",
    "Bookworm",
    "Menace13",
    "Oogapooki",
    "Mystic Deer",
    "OoDaShadowTheft",
    "Zachial",
    "Vivi",
    "BioBirb",
    "Qapples",
    "TacocaT",
    "Crusader",
    "Koda",
    "Codek",
    "Mystery Sol",
    "ZoraTK",
    "Spyker",
    "Tanko",
    "OoDa",
    "Ahntye",
    "Mr. Mutton",
    "Yeggy",
    "Sawtooth",
    "Syzygy",
    "Rift",
    "Frenchyy",
    "AdamGMAJ",
];
