export const allRCSMajors = {
    // "tournament/na-rcs-week-1/event/rivals-of-aether": "NA RCS Week 1",
    // "tournament/na-rcs-week-2/event/rivals-of-aether": "NA RCS Week 2",
    // "tournament/na-rcs-week-3/event/rivals-of-aether": "NA RCS Week 3",
    // "tournament/garden-of-gods-a-rivals-of-aether-national/event/rivals-of-aether-singles": "Garden of Gods - A Rivals of Aether National",
    // "tournament/na-rcs-week-4/event/rivals-of-aether": "NA RCS Week 4",
    // "tournament/na-rcs-week-5/event/rivals-of-aether": "NA RCS Week 5",
    // "tournament/na-rcs-week-6/event/rivals-of-aether": "NA RCS Week 6",
    // "tournament/guts-4-game-underground-tournament-spectacular-4/event/rivals-of-aether-singles": "GUTS 4 Game Underground Tournament Spectacular 4",
    // "tournament/na-rcs-week-7/event/rivals-of-aether": "NA RCS Week 7",
    // "tournament/rewired-2016-1/event/rivals-of-aether": "Rewired 2016",
    // "tournament/na-rcs-week-8/event/rivals-of-aether": "NA RCS Week 8",
    // "tournament/na-rcs-week-9/event/rivals-of-aether": "NA RCS Week 9",
    // "tournament/na-rcs-week-10/event/rivals-of-aether": "NA RCS Week 10",
    // "tournament/na-rcs-week-11/event/rivals-of-aether": "NA RCS Week 11",
    // "tournament/na-rcs-week-12/event/rivals-of-aether": "NA RCS Week 12",
    // "tournament/genesis-4/event/rivals-of-aether-singles": "Genesis 4",
    // "tournament/na-rcs-season-3-september-monthly/event/rivals-singles": "NA RCS Season 3 September Monthly",
    // "tournament/road-to-shine-rivals/event/qualifier-1-may-20th": "Road to Shine: Rivals",
    // "tournament/the-bigger-balc/event/rivals-of-aether-singles": "The Bigger Balc",
    // "tournament/road-to-shine-rivals/event/qualifier-2-june-10th": "Road to Shine: Rivals",
    // "tournament/na-rcs-july-monthly/event/rivals-of-aether-singles": "NA RCS July Monthly",
    // "tournament/low-tier-city-5/event/rivals-of-aether-singles": "Low Tier City 5",
    // "tournament/rivals-super-smash-con/event/rivals-of-aether-singles": "Rivals @ Super Smash Con",
    // "tournament/na-rcs-august-monthly/event/rivals-of-aether-singles": "NA RCS August Monthly",
    // "tournament/shine-2017/event/rivals-of-aether-singles": "Shine 2017",
    // "tournament/na-rcs-september-monthly/event/rivals-of-aether-singles": "NA RCS September Monthly",
    // "tournament/heat-wave/event/rivals-of-aether-singles": "Heat Wave",
    // "tournament/gametyrant-expo-2017/event/rivals-of-aether": "GameTyrant Expo 2017",
    // "tournament/na-rcs-october-monthly/event/rivals-of-aether-singles": "NA RCS October Monthly",
    // "tournament/na-rcs-november-monthly/event/rivals-of-aether-singles": "NA RCS November Monthly",
    // "tournament/na-rcs-december-monthly/event/rivals-of-aether-singles": "NA RCS December Monthly",
    // "tournament/genesis-5/event/rivals-of-aether": "Genesis 5",
    // "tournament/na-rcs-season-3-may-monthly-2/event/rivals-singles": "NA RCS Season 3 May Monthly",
    // "tournament/smash-n-splash-4/event/rivals-of-aether-singles": "Smash'N'Splash 4",
    // "tournament/na-rcs-season-3-june-monthly/event/rivals-singles": "NA RCS Season 3 June Monthly",
    // "tournament/2gg-hyrule-saga/event/rivals-of-aether": "2GG: Hyrule Saga",
    // "tournament/na-rcs-season-3-july-monthly/event/rivals-singles": "NA RCS Season 3 July Monthly",
    // "tournament/first-impact-2018/event/rivals-of-aether-singles": "First Impact 2018",
    // "tournament/rivals-at-super-smash-con-2018/event/rivals-of-aether-singles": "Rivals at Super Smash Con 2018",
    // "tournament/shine-2018/event/rivals-of-aether-singles": "Shine 2018",
    // "tournament/na-rcs-season-3-august-monthly/event/rivals-singles": "NA RCS Season 3 August Monthly",
    // "tournament/na-rcs-season-3-october-monthly/event/rivals-singles": "NA RCS Season 3 October Monthly",
    // "tournament/heat-wave-2/event/rivals-of-aether-singles": "Heat Wave 2",
    // "tournament/gametyrant-expo-2018/event/rivals-of-aether-1v1": "GameTyrant Expo 2018",
    // "tournament/na-rcs-season-3-november-monthly/event/rivals-singles": "NA RCS Season 3 November Monthly",
    // "tournament/na-rcs-season-3-december-monthly/event/rivals-singles": "NA RCS Season 3 December Monthly",
    // "tournament/don-t-park-on-the-grass-2018-1/event/rivals-of-aether-singles": "Don't Park on the Grass 2018",
    // "tournament/genesis-6/event/rivals-of-aether-singles": "Genesis 6",
    // "tournament/smash-n-splash-5/event/rivals-of-aether-singles-1-000-pot-bonus": "Smash'N'Splash 5",
    // "tournament/na-rcs-season-4-july-online-major/event/rivals-singles": "NA RCS Season 4 July Online Major",
    // "tournament/rivals-of-aether-at-evo-2019/event/rivals-singles": "Rivals of Aether at EVO 2019",
    // "tournament/indie-showcase-super-smash-con-2019/event/rivals-singles": "Indie Showcase @ Super Smash Con 2019",
    // "tournament/glitch-7-minus-world/event/rivals-singles": "Glitch 7 - Minus World",
    // "tournament/heat-wave-3/event/rivals-of-aether-singles": "Heat Wave 3",
    // "tournament/dreamhack-atlanta-2019/event/rivals-1v1": "DreamHack Atlanta 2019",
    // "tournament/na-rcs-season-4-december-online-major/event/rivals-singles": "NA RCS Season 4 December Online Major",
    // "tournament/genesis-7-1/event/rivals-of-aether-singles": "Genesis 7",
    // "tournament/rcs-season-5-fire/event/rivals-of-aether-singles": "RCS Season 5 - Fire",
    // "tournament/rcs-season-5-air/event/rivals-of-aether-singles": "RCS Season 5 - Air",
    // "tournament/rcs-season-5-earth/event/rivals-of-aether-singles": "RCS Season 5 - Earth",
    // "tournament/rcs-season-5-water/event/rivals-of-aether-singles": "RCS Season 5 - Water",
    // "tournament/na-rcs-finals/event/rivals-of-aether-singles": "NA RCS Finals",
    // "tournament/riptide-3/event/rivals-of-aether-singles": "Riptide",
    // "tournament/rcs-season-6-hot-springs/event/rivals-of-aether-singles": "RCS Season 6 - Hot Springs",
    // "tournament/rcs-season-6-melody/event/rivals-of-aether-singles": "RCS Season 6 - Melody",
    // "tournament/heat-wave-4/event/rivals-of-aether-singles": "Heat Wave 4",
    // "tournament/rcs-season-6-fireworks-1/event/rivals-of-aether-singles": "RCS Season 6 - Fireworks",
    // "tournament/rcs-season-6-crystal/event/rivals-of-aether-singles": "RCS Season 6 - Crystal",
    // "tournament/genesis-8/event/rivals-of-aether-singles": "Genesis 8",
    "tournament/gote-4thekids-7/event/rivals-of-aether-singles":
        "GoTE 4TheKids 7",
    "tournament/na-rcs-season-7-june-online-major/event/rivals-of-aether-singles":
        "RCS June Online Major",
    "tournament/double-down-2022/event/rivals-of-aether-singles":
        "Double Down 2022",
    "tournament/indie-showcase-ssc-2022/event/rivals-singles":
        "Super Smash Con 2022",
    "tournament/riptide-2022/event/rivals-of-aether-singles": "Riptide 2022",
    "tournament/the-big-house-10/event/rivals-of-aether-singles":
        "The Big House 10",
    "tournament/heat-wave-5/event/rivals-of-aether-singles": "Heat Wave 5",
    "tournament/na-rcs-season-7-december-online-major/event/rivals-of-aether-singles":
        "RCS December Online Major",
};

export const character_dict = {
    184: "Zetterburn",
    185: "Orcane",
    186: "Wrastor",
    187: "Kragg",
    188: "Forsburn",
    189: "Maypul",
    190: "Absa",
    191: "Etalus",
    1117: "Ori",
    1118: "Ranno",
    1119: "Clairen",
    1349: "Sylvanos",
    1350: "Elliana",
    1381: "SK",
    1920: "Mollo",
    1921: "Hodan",
    1922: "Pomme",
    1923: "Olympia",
};
