export const allRCSMajors = [
    // "tournament/na-rcs-week-1/event/rivals-of-aether",
    // "tournament/na-rcs-week-2/event/rivals-of-aether",
    // "tournament/na-rcs-week-3/event/rivals-of-aether",
    "tournament/garden-of-gods-a-rivals-of-aether-national/event/rivals-of-aether-singles",
    "tournament/na-rcs-week-4/event/rivals-of-aether",
    "tournament/na-rcs-week-5/event/rivals-of-aether",
    "tournament/na-rcs-week-6/event/rivals-of-aether",
    "tournament/guts-4-game-underground-tournament-spectacular-4/event/rivals-of-aether-singles",
    "tournament/na-rcs-week-7/event/rivals-of-aether",
    "tournament/rewired-2016-1/event/rivals-of-aether",
    "tournament/na-rcs-week-8/event/rivals-of-aether",
    "tournament/na-rcs-week-9/event/rivals-of-aether",
    "tournament/na-rcs-week-10/event/rivals-of-aether",
    "tournament/na-rcs-week-11/event/rivals-of-aether",
    "tournament/na-rcs-week-12/event/rivals-of-aether",
    "tournament/genesis-4/event/rivals-of-aether-singles",
    "tournament/na-rcs-season-3-september-monthly/event/rivals-singles",
    "tournament/road-to-shine-rivals/event/qualifier-1-may-20th",
    "tournament/the-bigger-balc/event/rivals-of-aether-singles",
    "tournament/road-to-shine-rivals/event/qualifier-2-june-10th",
    "tournament/na-rcs-july-monthly/event/rivals-of-aether-singles",
    "tournament/low-tier-city-5/event/rivals-of-aether-singles",
    "tournament/rivals-super-smash-con/event/rivals-of-aether-singles",
    "tournament/na-rcs-august-monthly/event/rivals-of-aether-singles",
    "tournament/shine-2017/event/rivals-of-aether-singles",
    "tournament/na-rcs-september-monthly/event/rivals-of-aether-singles",
    "tournament/heat-wave/event/rivals-of-aether-singles",
    "tournament/gametyrant-expo-2017/event/rivals-of-aether",
    "tournament/na-rcs-october-monthly/event/rivals-of-aether-singles",
    "tournament/na-rcs-november-monthly/event/rivals-of-aether-singles",
    "tournament/na-rcs-december-monthly/event/rivals-of-aether-singles",
    "tournament/genesis-5/event/rivals-of-aether",
    "tournament/na-rcs-season-3-may-monthly-2/event/rivals-singles",
    "tournament/smash-n-splash-4/event/rivals-of-aether-singles",
    "tournament/na-rcs-season-3-june-monthly/event/rivals-singles",
    "tournament/2gg-hyrule-saga/event/rivals-of-aether",
    "tournament/na-rcs-season-3-july-monthly/event/rivals-singles",
    "tournament/first-impact-2018/event/rivals-of-aether-singles",
    "tournament/rivals-at-super-smash-con-2018/event/rivals-of-aether-singles",
    "tournament/shine-2018/event/rivals-of-aether-singles",
    "tournament/na-rcs-season-3-august-monthly/event/rivals-singles",
    "tournament/na-rcs-season-3-october-monthly/event/rivals-singles",
    "tournament/heat-wave-2/event/rivals-of-aether-singles",
    "tournament/gametyrant-expo-2018/event/rivals-of-aether-1v1",
    "tournament/na-rcs-season-3-november-monthly/event/rivals-singles",
    "tournament/na-rcs-season-3-december-monthly/event/rivals-singles",
    "tournament/don-t-park-on-the-grass-2018-1/event/rivals-of-aether-singles",
    "tournament/genesis-6/event/rivals-of-aether-singles",
    "tournament/smash-n-splash-5/event/rivals-of-aether-singles-1-000-pot-bonus",
    "tournament/na-rcs-season-4-july-online-major/event/rivals-singles",
    "tournament/rivals-of-aether-at-evo-2019/event/rivals-singles",
    "tournament/indie-showcase-super-smash-con-2019/event/rivals-singles",
    "tournament/glitch-7-minus-world/event/rivals-singles",
    "tournament/heat-wave-3/event/rivals-of-aether-singles",
    "tournament/dreamhack-atlanta-2019/event/rivals-1v1",
    "tournament/na-rcs-season-4-december-online-major/event/rivals-singles",
    "tournament/genesis-7-1/event/rivals-of-aether-singles",
    "tournament/rcs-season-5-fire/event/rivals-of-aether-singles",
    "tournament/rcs-season-5-air/event/rivals-of-aether-singles",
    "tournament/rcs-season-5-earth/event/rivals-of-aether-singles",
    "tournament/rcs-season-5-water/event/rivals-of-aether-singles",
    "tournament/na-rcs-finals/event/rivals-of-aether-singles",
    "tournament/riptide-3/event/rivals-of-aether-singles",
    "tournament/rcs-season-6-hot-springs/event/rivals-of-aether-singles",
    "tournament/rcs-season-6-melody/event/rivals-of-aether-singles",
    "tournament/heat-wave-4/event/rivals-of-aether-singles",
    "tournament/rcs-season-6-fireworks-1/event/rivals-of-aether-singles",
    "tournament/rcs-season-6-crystal/event/rivals-of-aether-singles",
    "tournament/genesis-8/event/rivals-of-aether-singles",
    "tournament/gote-4thekids-7/event/rivals-of-aether-singles",
    "tournament/na-rcs-season-7-june-online-major/event/rivals-of-aether-singles",
    "tournament/double-down-2022/event/rivals-of-aether-singles",
    "tournament/indie-showcase-ssc-2022/event/rivals-singles",
    "tournament/riptide-2022/event/rivals-of-aether-singles",
    "tournament/the-big-house-10/event/rivals-of-aether-singles",
    "tournament/heat-wave-5/event/rivals-of-aether-singles",
    "tournament/na-rcs-season-7-december-online-major/event/rivals-of-aether-singles",
];

export const character_dict = {
    184: "Zetterburn",
    185: "Orcane",
    186: "Wrastor",
    187: "Kragg",
    188: "Forsburn",
    189: "Maypul",
    190: "Absa",
    191: "Etalus",
    1117: "Ori",
    1118: "Ranno",
    1119: "Clairen",
    1349: "Sylvanos",
    1350: "Elliana",
    1381: "SK",
    1920: "Mollo",
    1921: "Hodan",
    1922: "Pomme",
    1923: "Olympia",
};

export const unknownPlayers = [
    {
        tag: "LBO",
        startggID: "d51e7bc6",
    },
    {
        tag: "That_0ne_Guy",
        startggID: "78483bd4",
    },
    {
        tag: "Bicycle",
        startggID: "5549d5a9",
    },
    {
        tag: "SisterEden",
        startggID: "70557ea3",
    },
    {
        tag: "Gaming",
        startggID: "d023dd93",
    },
    {
        tag: "Roxol",
        startggID: "a8f3fa41",
    },
    {
        tag: "Gale Barret",
        startggID: "ead8f86e",
    },
    {
        tag: "XeroBox",
        startggID: "06465305",
    },
    {
        tag: "yesdefinitely",
        startggID: "3a356ccc",
    },
    {
        tag: "Joshyrachi",
        startggID: "0827454c",
    },
    {
        tag: "MasterIcarus7",
        startggID: "de069434",
    },
    {
        tag: "Nintega94",
        startggID: "9b98020b",
    },
    {
        tag: "Megapig9001",
        startggID: "3a4dd4ee",
    },
    {
        tag: "Ian",
        startggID: "f1bce0a7",
    },
    {
        tag: "Turquoise",
        startggID: "5965a0e1",
    },
    {
        tag: "MiNi",
        startggID: "7890f7b4",
    },
    {
        tag: "Zam",
        startggID: "67857952",
    },
    {
        tag: "Cluf",
        startggID: "blanklmao",
    },
];
